### ISSUE TITLE
Too visually different from screenshot

### ISSUE THREAD

**Issue by vanb0078** [vanb0078/modularity-mindfulness#2]
@anna-pokhilenko
@wendywarren

My banner image is not showing up on Markbot but it is showing up in Firefox. The article images are not aligning either and not sure why

<img width="857" alt="Screen Shot 2021-09-30 at 10 19 00 PM" src="https://user-images.githubusercontent.com/77505856/135555878-f4979b83-2501-4a90-808c-327c2a348781.png">
<img width="604" alt="Screen Shot 2021-09-30 at 10 19 35 PM" src="https://user-images.githubusercontent.com/77505856/135555885-0e8f682c-8f2a-4ad3-b9b8-4701a5f4bc6b.png">
.

**Comment by anna-pokhilenko** [comment]
Hello!

Markbot doesn't see the image, because it is placed in the header in your case. It wants you to put the img in main. 

<img width="676" alt="Screen Shot 2021-10-01 at 9 34 45 AM" src="https://user-images.githubusercontent.com/55008926/135628944-d104810a-b565-4a0b-8244-fbd0d3c47418.png">

To fix the issue with the imgs you will have to add a margin bottom to the images. I am attaching the fixing code for you.

<img width="424" alt="Screen Shot 2021-10-01 at 9 38 32 AM" src="https://user-images.githubusercontent.com/55008926/135629624-9253bc2c-b458-43e8-81cd-828a4c12d64d.png">

That should help.)
